server:
  port: 8086

spring:
  application:
    name: blog-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:postgresql://139.59.119.65:5432/5432/blogdb
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://139.59.119.65:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 146.190.90.222

