server:
  port: 8084

spring:
  application:
    name: payment-service
  cloud:
    discovery:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:139.59.119.65:9092}
      bindings:
        # consume OrderCreatedEvent
        orderCreated-in-0:
          destination: order-created
          group: payment-service-group
        # publish payment results
        paymentSucceeded-out-0:
          destination: payment-succeeded
        paymentFailed-out-0:
          destination: payment-failed
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 600000
    url: jdbc:postgresql://139.59.119.65:6432/paymentsdb
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka/}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://139.59.119.65:8090/realms/sketchnote



      payos:
        client-id: 1d3270ba-354d-4ac1-9693-09bd3ef01a47
        api-key: 8be8c8ef-3f5f-4fd8-ae46-4a170ca132e5
        checksum-key: f9386305d4e364c17bbe31b5beffeb99def6fa6da7ea63afc856301a8edbf851
