server:
  port: 8084

spring:
  application:
    name: payment-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paymentDB}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Thinh123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka/}
  instance:
      prefer-ip-address: true
      ip-address: 139.59.119.65


      payos:
        client-id: 1d3270ba-354d-4ac1-9693-09bd3ef01a47
        api-key: 8be8c8ef-3f5f-4fd8-ae46-4a170ca132e5
        checksum-key: f9386305d4e364c17bbe31b5beffeb99def6fa6da7ea63afc856301a8edbf851
