server:
  port: 8087

spring:
  application:
    name: project-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:postgresql://139.59.119.65:5432/projectdb
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka/}


